apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-server
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: eliasbedmar/dockerstack-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: clusterip-redis
            - name: REDIS_PORT
              value: '6379'
            - name: PGHOST
              value: clusterip-postgres
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
