apiVersion: v1
kind: Service
metadata:
  name: clusterip-client
spec:
  type: ClusterIP
  ports:
    - port: 3000 #Listening port
      targetPort: 3000 #(ContainerPort)
  selector:
    component: web
